name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate files
        run: |
          if [ ! -f public/index.html ]; then
            echo "::error::❌ Arquivo index.html não encontrado!"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Agora na raiz

      - name: Deploy
        uses: actions/deploy-pages@v2