name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify files
        run: |
          [ ! -f public/index.html ] && echo "::error::❌ index.html missing!" && exit 1
          echo "✅ Files verified"
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'
          
      - name: Deploy
        uses: actions/deploy-pages@v2